### PR TITLE
223: Add admin boolean

### LINKED ISSUE #223: De-jankify admin logic
Add boolean column

### PR DESCRIPTION
**Pull request by mikevallano**
## Related Issues & PRs
Closes #223

## Problems Solved
* Adds a proper boolean field to determine admins.

## Screenshots
N/A

## Things Learned
* We still don't have a way to _assign_ admin, but that's not going to be a problem for the foreseeable future. After the deploy, I'll update the records directly in the Rails console. I thought about doing it in the migration, but it seemed a bit insecure to add that in the codebase 🤷

### CODE REVIEW

**Review by lortza — APPROVED** [review]
This looks good to me. 👍  We may discover that we have more of this logic nested through a bunch of code, but i'm comfortable with deploying this now and then fixing bugs as they come up.

**Comment by mikevallano** [comment]
I'm sorry but I don't have 🐛 in my code 😆 .

**Comment by lortza** [comment]
Of _course_, of _course_. My mistake.

**Comment by lortza** [comment]
I noticed the schema file wasn't part of this PR. Might that be why Travis was having problems?

**Pull request merged**
